### ISSUE TITLE
Cannot use it in intellij.... Either I'm doing something wrong or it's broken but I can't even use the gradle

### ISSUE THREAD

**Issue by OhioSteak68** [Polyfrost/OneConfigExampleMod#7]
A problem occurred configuring root project 'ExampleMod'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.polyfrost:polyfrost-gradle-toolkit:0.2.9.
     Required by:
         project : > org.polyfrost.multi-version.root:org.polyfrost.multi-version.root.gradle.plugin:0.2.9
      > No matching variant of org.polyfrost:polyfrost-gradle-toolkit:0.2.9 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.4' but:
          - Variant 'apiElements' capability org.polyfrost:polyfrost-gradle-toolkit:0.2.9 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 16 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'runtimeElements' capability org.polyfrost:polyfrost-gradle-toolkit:0.2.9 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 16 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'sourcesElements' capability org.polyfrost:polyfrost-gradle-toolkit:0.2.9 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by nextdayy** [comment]
join discord.gg/polyfrost for support, or follow our docs at https://docs.polyfrost.org
